### ISSUE TITLE
Conflicting information about the licenses in the layout examples

### ISSUE THREAD

**Issue by KristjanESPERANTO** [pure-css/pure-site#445]
In the download file of the layout examples are two files with different license information: README.md indicates **zLib** and LICENSE.md indicates **BSD**. According to the issue #178 it's zLib, but in this case the LICENSE.md should be changed or removed, in my understanding.

**Comment by redonkulus** [comment]
Sorry for the confusion. All the example code is licensed under zlib since we expect users to download the code and modify it to fit their needs. There might be a bug in the code where its packaging the root license.md file which is BSD. We will need to bundle a zlib license file to avoid this issue.
